manifest:
  projects:
  - import: true
    name: zephyr
    revision: v4.2.0
    url: https://github.com/zephyrproject-rtos/zephyr
  - name: usp
    path: modules/lib/usp
    revision: main
    submodules: true
    url: https://github.com/Lora-net/usp.git
  self:
    path: application
