# Copyright (c) 2024 Semtech Corporation
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
  - import: true
    name: zephyr
    revision: v4.4.0
    url: https://github.com/zephyrproject-rtos/zephyr
  - name: usp
    path: modules/lib/usp
    revision: v1.2.1
    submodules: true
    url: https://github.com/Lora-net/usp.git
  self:
    path: application
