# Copyright (c) 2026 Semtech Corporation
# SPDX-License-Identifier: Apache-2.0

# ------------------------------ Xiao ESP32-S3 -----------------------------

#Use immediate log mode to avoid a logging stack overflow
CONFIG_LOG_MODE_IMMEDIATE=y
